In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=sns.load_dataset('iris')

In [3]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x=df.drop('species', axis=1)
y=df['species']

In [7]:
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.33,random_state=42
)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
model_knn=KNeighborsClassifier(n_neighbors=13)

In [10]:
model_knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [11]:
y_pred=model_knn.predict(x_test)

In [12]:
model_knn.score(x_test,y_test)

1.0

In [13]:
from sklearn.svm import SVC

In [14]:
model_svm=SVC()

In [15]:
model_svm.fit(x_train,y_train)

SVC()

In [16]:
model_svm.score(x_test,y_test)

1.0

In [17]:
from sklearn.model_selection import GridSearchCV

In [18]:
classifier=GridSearchCV((model_svm),{'C':[1,10,20,30],'kernel':['rbf','linear']},cv=5,return_train_score=False)

In [19]:
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [20]:
classifier.cv_results_

{'mean_fit_time': array([0.00575323, 0.00433598, 0.00402527, 0.00319505, 0.0040494 ,
        0.0033    , 0.00342288, 0.00372062]),
 'std_fit_time': array([1.73024585e-03, 5.53138063e-04, 6.43276821e-04, 6.47156041e-05,
        8.23669543e-04, 1.84468102e-04, 1.80307925e-04, 5.79053375e-04]),
 'mean_score_time': array([0.00398808, 0.00279408, 0.00280743, 0.0023746 , 0.00281496,
        0.00238853, 0.00260611, 0.00262394]),
 'std_score_time': array([1.32754629e-03, 9.21604728e-05, 3.11791249e-04, 1.43878452e-05,
        3.21505183e-04, 7.51578259e-05, 2.54709048e-04, 2.34987635e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([0.96666667, 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        ]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.96666667,
        0.9       , 0.93333333, 0.9       ]),
 'split3_test_score': array([0.93333333, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.96666667, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.96666667, 0.98      , 0.98      , 0.97333333, 0.98      ,
        0.96666667, 0.97333333, 0.96      ]),
 'std_test_score': array([0.02108185, 0.01632993, 0.01632993, 0.03887301, 0.01632993,
        0.0421637 , 0.02494438, 0.04898979]),
 'rank_test_score': array([6, 1, 1, 4, 1, 6, 4, 8], dtype=int32)}

In [21]:
result=pd.DataFrame(classifier.cv_results_)

In [22]:
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005753,0.001730,0.003988,0.001328,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,0.966667,0.966667,0.933333,1.0,0.966667,0.021082,6
1,0.004336,0.000553,0.002794,0.000092,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004025,0.000643,0.002807,0.000312,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003195,0.000065,0.002375,0.000014,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.004049,0.000824,0.002815,0.000322,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
5,0.003300,0.000184,0.002389,0.000075,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.003423,0.000180,0.002606,0.000255,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,4
7,0.003721,0.000579,0.002624,0.000235,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,8

In [23]:
from sklearn.model_selection import RandomizedSearchCV

In [24]:
classifer=RandomizedSearchCV(estimator=model_svm,param_distributions={'C':[1,10,20,30],'kernel':['rbf','linear']},cv=5,return_train_score=False,n_iter=4)

In [25]:
model_svm.fit(x_train,y_train)

SVC()

In [26]:
classifer.fit(x,y)

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [27]:
y_pred=model_svm.predict(x_test)

In [28]:
y_pred

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa', 'setosa', 'setosa',
       'versicolor', 'setosa', 'setosa', 'virginica', 'versicolor',
       'setosa', 'setosa', 'setosa', 'virginica', 'versicolor',
       'versicolor', 'setosa', 'setosa', 'versicolor', 'virginica',
       'virginica', 'versicolor', 'virginica'], dtype=object)